name: CI Feature

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/**'

jobs:
  backend:
    name: Backend - Build, Test & Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Build backend
        working-directory: ./backend/
        run: mvn clean install -DskipTests

      - name: Run unit tests
        working-directory: ./backend
        run: mvn -B clean test -Dtest=**/unit/**/*Test.java


  frontend:
    name: Frontend - Build & Test 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Build frontend
        working-directory: ./frontend/
        run: |
          npm ci
          npm run build

      - name: Run frontend tests 
        working-directory: ./frontend
        env:
          CI: true
        run: npm run test -- --watch=false --browsers=ChromeHeadless --include=src/app/components/**/*.spec.ts

